# version: '3'
# services:
#   server:
#     build: 
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - 5001:5001
#   client:
#     build: 
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000

version: '3'
services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 5001:5001

  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
